### PR TITLE
Additional basic testing

### PR DESCRIPTION
**Pull request by hidetak**
Basic tests were added.

* Performed only on binding-http
* Performed only the following 4 tests with both server-side and client-side nodes
  * read property
  * write property
  * invoke action
  * subscribe event

~~I have restarted Node-RED twice during the test, but I get errors, probably because the HTTP server fails to stop.
However, the test succeeds.~~
When subscribing, the client retries if the connection to the server fails.
During testing, an error may be displayed if a connection from the client fails due to a server restart.

Tests are now run automatically when a pull request is created.

### CODE REVIEW

**Comment by egekorkan** [comment]
For subscribeevent and observeproperty I get the following error:

> [error] subscribe events. FetchError: request to http://127.0.0.1:8383/thing01/events/testEvent failed, reason: connect ECONNREFUSED 127.0.0.1:8383
at ClientRequest.<anonymous> (/Users/egekorkan/git/node-red/node-red-node-wot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:519:28)
    at ClientRequest.emit (node:domain:488:12)
    at Socket.socketErrorListener (node:_http_client:492:9)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}

However, even then I see `✔ subscribe event`

**Comment by hidetak** [comment]
@egekorkan 
Thank you for your confirmation.

This error occurs when a client connection is made before the server has finished starting.
The client retries when this error occurs, so the test succeeds.

**Comment by hidetak** [comment]
@egekorkan 
After the following PRs are merged, I will maintain the code for this PR.
https://github.com/eclipse-thingweb/node-red/pull/4

**Comment by egekorkan** [comment]
> @egekorkan 
> After the following PRs are merged, I will maintain the code for this PR.
> https://github.com/eclipse-thingweb/node-red/pull/4

That PR is now merged. Do you want to adapt this one @hidetak ?

**Comment by hidetak** [comment]
@egekorkan 

> That PR is now merged. Do you want to adapt this one @hidetak ?

Yes, I would like to.
If publishing is a priority, I don't see a problem with putting it in the next release.
I think I can have it ready by the end of this week at the latest.

**Comment by egekorkan** [comment]
> I think I can have it ready by the end of this week at the latest.

We can wait that much, thank you once again!

**Comment by hidetak** [comment]
@egekorkan 
I have modified this branch so that it can be merged into the main branch.
Sorry for the difficulty in tracking the commits. 
The difference from the main branch should be as follows:
https://github.com/eclipse-thingweb/node-red/pull/3/commits/08a07c31dbad9231750e60c9b184ca8d77c0461e

**Review by egekorkan — APPROVED** [review]

**Comment by egekorkan** [comment]
@hidetak it is looking good! Thank you very much

**Pull request merged**
