### PR TITLE
refactor: use detectProtocolSchemes from @thingweb/td-utils for check…

### LINKED ISSUE #17: Refactor binding finder
> After the discussions today, a real solution will take some time land and I would not want to block this PR. I propose to merge this PR and create an issue to track this. Once https://github.com/eclipse-thingweb/td-tools/issues/18 is done, we can do the work to integrate it here. @danielpeintner @relu91 any opinions?

_Originally posted by @egekorkan in https://github.com/eclipse-thingweb/node-red/pull/16#discussion_r1581000782_

### PR DESCRIPTION
**Pull request by hasanheroglu**
- I replaced the logic in checkBinding funciton with detectProtocolSchemes from @thingweb/td-utils.
- I was not able to test since I am not familiar with node-red. Maybe I can get help with that.
- Closes #17

### CODE REVIEW

**Review by egekorkan — APPROVED** [review]
Looks fine, thanks @hasanheroglu ! @hidetak do you want to review this PR as well?

**Comment by hidetak** [comment]
@hasanheroglu @egekorkan 

Thank you for the modification to use the function to identify scheme.
However, the following file you modified works on the browser, so it does not work with this modification.
https://github.com/eclipse-thingweb/node-red/pull/29/files#diff-0526a17883259568e0d7d1609bba55d655b6ef96bb18868624fe7a04ec3bb4ce

**Comment by hasanheroglu** [comment]
Hey @hidetak, 

I made some changes, tested it locally, and it seems to work fine. 
I added an extra command to the build script of the plugin to copy td-utils library to the resources folder so the library can be accessible in the browser.
The solution may not be very neat, but it was the only one I could come up with.
Let me know what you think.
If you like the solution, before we close this merge request, I can also use the same library to substitute `checkBinding` functions in nodes.

**Comment by hidetak** [comment]
@hasanheroglu 

Thank you for your consideration!
It looks like we can directly include `web-bundle.min.js` from cdn below.
https://cdn.jsdelivr.net/npm/@thingweb/td-utils@1.0.0/dist/web-bundle.min.js

However, I think the method you modified is better because it can be used in environments where there is no Internet connection or where a proxy is required.

> If you like the solution, before we close this merge request, I can also use the same library to substitute checkBinding functions in nodes.

Thank you very much !
You may already know this, but the following may be a description of how to use the js file from a node.
https://nodered.org/docs/creating-nodes/resources

**Review by hidetak — APPROVED** [review]
Thank you for the correction!

**Pull request merged**
